# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - veiko.vunder@ut.ee
branches:
  only:
  - melodic-devel
  - melodic-devel-maarika
  - melodic-devel-veiko
env:
  global: # global settings for all jobs
    - ROS_REPO=ros
    - CCACHE_DIR=$HOME/.ccache # enables C/C++ caching in industrial_ci
  matrix:
    - ROS_DISTRO="kinetic" UPSTREAM_WORKSPACE='github:robotont/robotont_description#melodic-devel'
    - ROS_DISTRO="melodic" UPSTREAM_WORKSPACE='github:robotont/robotont_description#melodic-devel'
install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
