<?xml version="1.0"?>
<package format="2">
  <name>robotont_nuc_description</name>
  <version>0.0.3</version>
  <description>The robotont_nuc_description package</description>

  <maintainer email="veiko.vunder@ut.ee">Veiko Vunder</maintainer>
  <maintainer email="karl.kruusamae@ut.ee">Karl Kruusamäe</maintainer>

  <url type="website">https://wiki.ros.org/robotont</url>
  <url type="website">https://robotont.ut.ee</url>
  <url type="repository">https://github.com/robotont/robotont_nuc_description</url>

  <license>Apache 2.0</license>
  
  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <exec_depend>robotont_description</exec_depend>
  <exec_depend>realsense2_description</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>xacro</exec_depend>
 
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
