name: build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: workspace

      - name: Configure VCS
        run: |
          python3 -m pip install --upgrade pip
          pip install vcstool

      - name: Fetch dependencies
        run: |
          cd workspace
          vcs import src < dependencies.repos

      - name: Build ROS2 Workspace
        uses: ichiro-its/ros2-ws-action@v1.0.0
        with:
          distro: jazzy